CharacterTemplateProxy = ResourceProxy:new()
CharacterTemplateProxy.fieldsToParse = {
	"ActivationGroupId",
	"AliveInventoryType",
	"AnubisConfigName",
	"AvoidTraps",
	"CanBePickpocketed",
	"CanBeTeleported",
	"CanClimbLadders",
	"CanConsumeItems",
	"CanOpenDoors",
	"CanShootThrough",
	"CanWalkThroughDoors",
	["CombatComponent"] = {
		"Archetype",
		"CanFight",
		"CanJoinCombat",
		"CombatGroupID",
		"Faction",
		"IsBoss",
		"StartCombatRange",
		"StayInAiHints",
		"SwarmGroup",
	},
	"CoverAmount",
	"CriticalHitType",
	"DefaultState",
	"DisableEquipping",
	"Equipment",
	"ExcludeInDifficulty",
	"InventoryType",
	"IsDroppedOnDeath",
	"IsEquipmentLootable",
	"IsLootable",
	"IsMovementEnabled",
	"IsSimpleCharacter",
	"IsTradable",
	"ItemList",
	"LevelOverride",
	"MaxDashDistance",
	"OnlyInDifficulty",
	"Race",
	"SkillList",
	"SpellSet",
	"SpotSneakers",
	"Stats",
	"StatusList",
	"Title",
	"TradeTreasures",
	"Treasures",
	"TrophyID",
	"WalkThrough",
}


ResourceProxy:RegisterResourceProxy("CharacterTemplate", CharacterTemplateProxy)
