EntityHandleProxy = EntityProxy:new()
EntityHandleProxy.fieldsToParse = {
	"ActionResources",
	"AddedSpells",
	"AttitudesToPlayers",
	"AttributeFlags",
	"AvailableLevel",
	"BaseHp",
	"BaseStats",
	"BoostsContainer",
	"Bound",
	"CanBeDisarmed",
	"CanBeLooted",
	"CanBeWielded",
	"CanDeflectProjectiles",
	"CanDoActions",
	"CanEnterChasm",
	"CanInteract",
	"CanModifyHealth",
	"CanMove",
	"CanSeeThrough",
	"CanSense",
	"CanSpeak",
	"CanTravel",
	"CanTriggerRandomCasts",
	"Classes",
	"CombatParticipant",
	"Concentration",
	"Darkness",
	"Data",
	"DifficultyCheck",
	"DisplayName",
	"DualWielding",
	"EncumbranceState",
	"EncumbranceStats",
	"EocLevel",
	"Expertise",
	"Faction",
	"FleeCapability",
	"HealBlock",
	"Health",
	"Hearing",
	"Icon",
	"InterruptContainer",
	"InterruptPreferences",
	"Invisibility",
	"LearnedSpells",
	"Level",
	"LevelUp",
	"Loot",
	"Movement",
	"ObjectInteraction",
	"ObjectSize",
	"OriginalTemplate",
	"PassiveContainer",
	"Proficiency",
	"ProgressionContainer",
	"Race",
	"Resistances",
	"ServerAiArchetype",
	"ServerAnubisExecutor",
	"ServerAnubisTag",
	"ServerBaseData",
	"ServerBaseProficiency",
	"ServerBaseSize",
	"ServerBaseStats",
	"ServerBoostBase",
	"ServerBoostTag",
	"ServerCanStartCombat",
	"ServerDelayDeathCause",
	"ServerOsirisTag",
	"ServerPassiveBase",
	"ServerPassivePersistentData",
	"ServerPickpocket",
	"ServerRaceTag",
	"ServerReplicationDependencyOwner",
	"ServerSafePosition",
	"ServerShapeshiftStates",
	"ServerStatusDifficultyModifiers",
	"ServerTemplateTag",
	"ShapeshiftHealthReservation",
	"SpellAiConditions",
	"SpellBook",
	"SpellBookCooldowns",
	"SpellBookPrepares",
	"SpellCastCanBeTargeted",
	"SpellContainer",
	"Stats",
	"StatusImmunities",
	"SurfacePathInfluences",
	"Tag",
	"Uuid",
	"WeaponSet"
}


EntityProxy:RegisterResourceProxy("Entity", EntityHandleProxy)

---@param entityId GUIDSTRING
function EntityProxy:RenderDisplayWindow(entityId, parent)
	Channels.GetEntityDump:RequestToServer({
		entity = entityId,
		fields = self.fieldsToParse
	}, function(data)
		self:RenderDisplayWindow(data, parent)
	end)
end
